import { PokemonAbility } from './PokemonComponents/Ability';
import { PokemonCries } from './PokemonComponents/Cries';
import { VersionGameIndex } from './PokemonComponents/GameIndex';
import { NamedApiResource } from './PokemonComponents/GenericApiResponse';
import { PokemonHeldItem } from './PokemonComponents/HeldItem';
import { PokemonMove } from './PokemonComponents/Move';
import { PokemonTypePast } from './PokemonComponents/PastType';
import { PokemonSprites } from './PokemonComponents/Sprite';
import { PokemonStat } from './PokemonComponents/Stat';
import { PokemonType } from './PokemonComponents/Type';

export type Pokemon = {
  id: number;
  name: string;
  base_experience: number;
  height: number;
  is_default: boolean;
  order: number;
  weight: number;
  abilities: Array<PokemonAbility>;
  forms: Array<NamedApiResource>;
  game_indices: Array<VersionGameIndex>;
  held_items: Array<PokemonHeldItem>;
  location_area_encounters: string;
  moves: Array<PokemonMove>;
  past_types: Array<PokemonTypePast>;
  sprites: PokemonSprites;
  cries: PokemonCries;
  species: NamedApiResource;
  stats: Array<PokemonStat>;
  types: Array<PokemonType>;
};
